// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMDNMxFsbBBOZBVZYR8HVS67-smA65Z6g',
    appId: '1:426519737249:web:1dafb1d969496d4d3a51e0',
    messagingSenderId: '426519737249',
    projectId: 'vehicle-damage-roadresq',
    authDomain: 'vehicle-damage-roadresq.firebaseapp.com',
    storageBucket: 'vehicle-damage-roadresq.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIizuNLQg5DBg1um16x-77z9rN1TZorQ8',
    appId: '1:426519737249:android:a27b405caddd5d2a3a51e0',
    messagingSenderId: '426519737249',
    projectId: 'vehicle-damage-roadresq',
    storageBucket: 'vehicle-damage-roadresq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyTdkaKpGgrkDcoPgaq8mfY_2xFJQXXfI',
    appId: '1:426519737249:ios:55f9b0f161f4a2583a51e0',
    messagingSenderId: '426519737249',
    projectId: 'vehicle-damage-roadresq',
    storageBucket: 'vehicle-damage-roadresq.firebasestorage.app',
    iosBundleId: 'com.example.launcherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyTdkaKpGgrkDcoPgaq8mfY_2xFJQXXfI',
    appId: '1:426519737249:ios:55f9b0f161f4a2583a51e0',
    messagingSenderId: '426519737249',
    projectId: 'vehicle-damage-roadresq',
    storageBucket: 'vehicle-damage-roadresq.firebasestorage.app',
    iosBundleId: 'com.example.launcherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMDNMxFsbBBOZBVZYR8HVS67-smA65Z6g',
    appId: '1:426519737249:web:56a83313d5acf3a03a51e0',
    messagingSenderId: '426519737249',
    projectId: 'vehicle-damage-roadresq',
    authDomain: 'vehicle-damage-roadresq.firebaseapp.com',
    storageBucket: 'vehicle-damage-roadresq.firebasestorage.app',
  );
}
