// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNWnqyYCWYIiNg5x5mFgyrxsorumC2Rfw',
    appId: '1:280142879390:android:64798e6b0a0dd36456398f',
    messagingSenderId: '280142879390',
    projectId: 'guardian-link-6bece',
    databaseURL: 'https://guardian-link-6bece-default-rtdb.firebaseio.com',
    storageBucket: 'guardian-link-6bece.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHkqGBMMSKVx-05c2MIsY3mDhOxs0tDvw',
    appId: '1:280142879390:ios:a59d4c44b5621fe556398f',
    messagingSenderId: '280142879390',
    projectId: 'guardian-link-6bece',
    databaseURL: 'https://guardian-link-6bece-default-rtdb.firebaseio.com',
    storageBucket: 'guardian-link-6bece.firebasestorage.app',
    iosBundleId: 'com.guardianlink.guardianLink',
  );
}
